### ISSUE TITLE
undefined method `[]' 3.0.23

### ISSUE THREAD

**Issue by juniovitorino** [backup/backup#297]
I'm getting this weird error after update to 3.0.23, the output not help so much, but it's bellow. 

The ruby version is 1.9.2-p182

```
[2012/03/28 17:05:56][message] Storage::SCP: Cycling Started...
[2012/03/28 17:05:57][error] ModelError: Backup for Lider Interiores Backup (lider_cloud_backup) Failed!
[2012/03/28 17:05:57][error]   An Error occured which has caused this Backup to abort before completion.
[2012/03/28 17:05:57][error]   Reason: NoMethodError
[2012/03/28 17:05:57][error]   undefined method `[]' for nil:NilClass
[2012/03/28 17:05:57][error] 
[2012/03/28 17:05:57][error] Backtrace:
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/backup-3.0.23/lib/backup/storage/cycler.rb:94:in `block in check_upgrade'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/backup-3.0.23/lib/backup/storage/cycler.rb:92:in `map!'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/backup-3.0.23/lib/backup/storage/cycler.rb:92:in `check_upgrade'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/backup-3.0.23/lib/backup/storage/cycler.rb:71:in `yaml_load'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/backup-3.0.23/lib/backup/storage/cycler.rb:27:in `update_storage_file!'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/backup-3.0.23/lib/backup/storage/cycler.rb:17:in `cycle!'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/backup-3.0.23/lib/backup/storage/base.rb:93:in `cycle!'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/backup-3.0.23/lib/backup/storage/base.rb:34:in `perform!'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/backup-3.0.23/lib/backup/model.rb:245:in `each'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/backup-3.0.23/lib/backup/model.rb:245:in `block in perform!'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/backup-3.0.23/lib/backup/model.rb:243:in `each'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/backup-3.0.23/lib/backup/model.rb:243:in `perform!'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/backup-3.0.23/lib/backup/cli/utility.rb:74:in `block in perform'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/backup-3.0.23/lib/backup/cli/utility.rb:65:in `each'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/backup-3.0.23/lib/backup/cli/utility.rb:65:in `perform'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
[2012/03/28 17:05:57][error]   /usr/local/ruby/lib/ruby/gems/1.9.1/gems/backup-3.0.23/bin/backup:11:in `<top (required)>'
[2012/03/28 17:05:57][error]   /usr/local/ruby/bin/backup:19:in `load'
[2012/03/28 17:05:57][error]   /usr/local/ruby/bin/backup:19:in `<main>'
```
