### ISSUE TITLE
Campfire does not work on 1.8 series ruby

### ISSUE THREAD

**Issue by courtenay** [backup/backup#507]
The problem is with the Excon library and http auth:

```
[2013/11/21 23:01:40][info] NoMethodError: undefined method `decode_www_form_component' for URI:Module
```

This method was only introduced in 1.9 URI. Rack::Utils has implemented a workaround, though; I've also opened a ticket with Excon, since that's probably the only way this will get fixed.
